
namespace SanatGalerisi
{
    partial class frmMuzayedeEkle
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMuzayedeEkle));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.txtAdi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSoyad = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTelefon = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMuzayedeAdi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMuzayedeBaslangic = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMuzayedeBitis = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnKaydet = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.radioButton1 = new System.Windows.Forms.RadioButton();
            this.txtUcret = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.lblUcret = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnHesapla = new Bunifu.Framework.UI.BunifuThinButton2();
            this.txtBitis = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtBaslangic = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // txtAdi
            // 
            this.txtAdi.AcceptsReturn = false;
            this.txtAdi.AcceptsTab = false;
            this.txtAdi.AnimationSpeed = 200;
            this.txtAdi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAdi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAdi.AutoSizeHeight = true;
            this.txtAdi.BackColor = System.Drawing.Color.Transparent;
            this.txtAdi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAdi.BackgroundImage")));
            this.txtAdi.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtAdi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtAdi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtAdi.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtAdi.BorderRadius = 1;
            this.txtAdi.BorderThickness = 1;
            this.txtAdi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAdi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdi.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAdi.DefaultText = "";
            this.txtAdi.FillColor = System.Drawing.Color.White;
            this.txtAdi.HideSelection = true;
            this.txtAdi.IconLeft = null;
            this.txtAdi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdi.IconPadding = 10;
            this.txtAdi.IconRight = null;
            this.txtAdi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdi.Lines = new string[0];
            this.txtAdi.Location = new System.Drawing.Point(42, 40);
            this.txtAdi.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtAdi.MaxLength = 30;
            this.txtAdi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAdi.Modified = false;
            this.txtAdi.Multiline = false;
            this.txtAdi.Name = "txtAdi";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdi.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAdi.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdi.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdi.OnIdleState = stateProperties4;
            this.txtAdi.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtAdi.PasswordChar = '\0';
            this.txtAdi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAdi.PlaceholderText = "Adı";
            this.txtAdi.ReadOnly = false;
            this.txtAdi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAdi.SelectedText = "";
            this.txtAdi.SelectionLength = 0;
            this.txtAdi.SelectionStart = 0;
            this.txtAdi.ShortcutsEnabled = true;
            this.txtAdi.Size = new System.Drawing.Size(250, 46);
            this.txtAdi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAdi.TabIndex = 0;
            this.txtAdi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAdi.TextMarginBottom = 0;
            this.txtAdi.TextMarginLeft = 3;
            this.txtAdi.TextMarginTop = 1;
            this.txtAdi.TextPlaceholder = "Adı";
            this.txtAdi.UseSystemPasswordChar = false;
            this.txtAdi.WordWrap = true;
            this.txtAdi.TextChanged += new System.EventHandler(this.txtAdi_TextChanged);
            // 
            // txtSoyad
            // 
            this.txtSoyad.AcceptsReturn = false;
            this.txtSoyad.AcceptsTab = false;
            this.txtSoyad.AnimationSpeed = 200;
            this.txtSoyad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoyad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoyad.AutoSizeHeight = true;
            this.txtSoyad.BackColor = System.Drawing.Color.Transparent;
            this.txtSoyad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoyad.BackgroundImage")));
            this.txtSoyad.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtSoyad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtSoyad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtSoyad.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtSoyad.BorderRadius = 1;
            this.txtSoyad.BorderThickness = 1;
            this.txtSoyad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoyad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoyad.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSoyad.DefaultText = "";
            this.txtSoyad.FillColor = System.Drawing.Color.White;
            this.txtSoyad.HideSelection = true;
            this.txtSoyad.IconLeft = null;
            this.txtSoyad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoyad.IconPadding = 10;
            this.txtSoyad.IconRight = null;
            this.txtSoyad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoyad.Lines = new string[0];
            this.txtSoyad.Location = new System.Drawing.Point(42, 94);
            this.txtSoyad.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtSoyad.MaxLength = 30;
            this.txtSoyad.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoyad.Modified = false;
            this.txtSoyad.Multiline = false;
            this.txtSoyad.Name = "txtSoyad";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoyad.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoyad.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoyad.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoyad.OnIdleState = stateProperties8;
            this.txtSoyad.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtSoyad.PasswordChar = '\0';
            this.txtSoyad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoyad.PlaceholderText = "Soyadı";
            this.txtSoyad.ReadOnly = false;
            this.txtSoyad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoyad.SelectedText = "";
            this.txtSoyad.SelectionLength = 0;
            this.txtSoyad.SelectionStart = 0;
            this.txtSoyad.ShortcutsEnabled = true;
            this.txtSoyad.Size = new System.Drawing.Size(250, 46);
            this.txtSoyad.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoyad.TabIndex = 1;
            this.txtSoyad.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoyad.TextMarginBottom = 0;
            this.txtSoyad.TextMarginLeft = 3;
            this.txtSoyad.TextMarginTop = 1;
            this.txtSoyad.TextPlaceholder = "Soyadı";
            this.txtSoyad.UseSystemPasswordChar = false;
            this.txtSoyad.WordWrap = true;
            this.txtSoyad.TextChanged += new System.EventHandler(this.txtSoyad_TextChanged);
            // 
            // txtTC
            // 
            this.txtTC.AcceptsReturn = false;
            this.txtTC.AcceptsTab = false;
            this.txtTC.AnimationSpeed = 200;
            this.txtTC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTC.AutoSizeHeight = true;
            this.txtTC.BackColor = System.Drawing.Color.Transparent;
            this.txtTC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTC.BackgroundImage")));
            this.txtTC.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtTC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtTC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtTC.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtTC.BorderRadius = 1;
            this.txtTC.BorderThickness = 1;
            this.txtTC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTC.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTC.DefaultText = "";
            this.txtTC.FillColor = System.Drawing.Color.White;
            this.txtTC.HideSelection = true;
            this.txtTC.IconLeft = null;
            this.txtTC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTC.IconPadding = 10;
            this.txtTC.IconRight = null;
            this.txtTC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTC.Lines = new string[0];
            this.txtTC.Location = new System.Drawing.Point(42, 148);
            this.txtTC.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtTC.MaxLength = 11;
            this.txtTC.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTC.Modified = false;
            this.txtTC.Multiline = false;
            this.txtTC.Name = "txtTC";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTC.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTC.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTC.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTC.OnIdleState = stateProperties12;
            this.txtTC.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtTC.PasswordChar = '\0';
            this.txtTC.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTC.PlaceholderText = "TC";
            this.txtTC.ReadOnly = false;
            this.txtTC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTC.SelectedText = "";
            this.txtTC.SelectionLength = 0;
            this.txtTC.SelectionStart = 0;
            this.txtTC.ShortcutsEnabled = true;
            this.txtTC.Size = new System.Drawing.Size(250, 46);
            this.txtTC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTC.TabIndex = 2;
            this.txtTC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTC.TextMarginBottom = 0;
            this.txtTC.TextMarginLeft = 3;
            this.txtTC.TextMarginTop = 1;
            this.txtTC.TextPlaceholder = "TC";
            this.txtTC.UseSystemPasswordChar = false;
            this.txtTC.WordWrap = true;
            // 
            // txtTelefon
            // 
            this.txtTelefon.AcceptsReturn = false;
            this.txtTelefon.AcceptsTab = false;
            this.txtTelefon.AnimationSpeed = 200;
            this.txtTelefon.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefon.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefon.AutoSizeHeight = true;
            this.txtTelefon.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefon.BackgroundImage")));
            this.txtTelefon.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtTelefon.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtTelefon.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtTelefon.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtTelefon.BorderRadius = 1;
            this.txtTelefon.BorderThickness = 1;
            this.txtTelefon.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefon.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelefon.DefaultText = "";
            this.txtTelefon.FillColor = System.Drawing.Color.White;
            this.txtTelefon.HideSelection = true;
            this.txtTelefon.IconLeft = null;
            this.txtTelefon.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.IconPadding = 10;
            this.txtTelefon.IconRight = null;
            this.txtTelefon.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.Lines = new string[0];
            this.txtTelefon.Location = new System.Drawing.Point(42, 202);
            this.txtTelefon.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtTelefon.MaxLength = 11;
            this.txtTelefon.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefon.Modified = false;
            this.txtTelefon.Multiline = false;
            this.txtTelefon.Name = "txtTelefon";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefon.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnIdleState = stateProperties16;
            this.txtTelefon.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtTelefon.PasswordChar = '\0';
            this.txtTelefon.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefon.PlaceholderText = "Telefon";
            this.txtTelefon.ReadOnly = false;
            this.txtTelefon.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefon.SelectedText = "";
            this.txtTelefon.SelectionLength = 0;
            this.txtTelefon.SelectionStart = 0;
            this.txtTelefon.ShortcutsEnabled = true;
            this.txtTelefon.Size = new System.Drawing.Size(250, 46);
            this.txtTelefon.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefon.TabIndex = 3;
            this.txtTelefon.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefon.TextMarginBottom = 0;
            this.txtTelefon.TextMarginLeft = 3;
            this.txtTelefon.TextMarginTop = 1;
            this.txtTelefon.TextPlaceholder = "Telefon";
            this.txtTelefon.UseSystemPasswordChar = false;
            this.txtTelefon.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(42, 256);
            this.txtEmail.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtEmail.MaxLength = 25;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties20;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Email";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(250, 46);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 4;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "Email";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtMuzayedeAdi
            // 
            this.txtMuzayedeAdi.AcceptsReturn = false;
            this.txtMuzayedeAdi.AcceptsTab = false;
            this.txtMuzayedeAdi.AnimationSpeed = 200;
            this.txtMuzayedeAdi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMuzayedeAdi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMuzayedeAdi.AutoSizeHeight = true;
            this.txtMuzayedeAdi.BackColor = System.Drawing.Color.Transparent;
            this.txtMuzayedeAdi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMuzayedeAdi.BackgroundImage")));
            this.txtMuzayedeAdi.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtMuzayedeAdi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtMuzayedeAdi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtMuzayedeAdi.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtMuzayedeAdi.BorderRadius = 1;
            this.txtMuzayedeAdi.BorderThickness = 1;
            this.txtMuzayedeAdi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMuzayedeAdi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeAdi.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMuzayedeAdi.DefaultText = "";
            this.txtMuzayedeAdi.FillColor = System.Drawing.Color.White;
            this.txtMuzayedeAdi.HideSelection = true;
            this.txtMuzayedeAdi.IconLeft = null;
            this.txtMuzayedeAdi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeAdi.IconPadding = 10;
            this.txtMuzayedeAdi.IconRight = null;
            this.txtMuzayedeAdi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeAdi.Lines = new string[0];
            this.txtMuzayedeAdi.Location = new System.Drawing.Point(42, 310);
            this.txtMuzayedeAdi.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtMuzayedeAdi.MaxLength = 20;
            this.txtMuzayedeAdi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMuzayedeAdi.Modified = false;
            this.txtMuzayedeAdi.Multiline = false;
            this.txtMuzayedeAdi.Name = "txtMuzayedeAdi";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeAdi.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMuzayedeAdi.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeAdi.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeAdi.OnIdleState = stateProperties24;
            this.txtMuzayedeAdi.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtMuzayedeAdi.PasswordChar = '\0';
            this.txtMuzayedeAdi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMuzayedeAdi.PlaceholderText = "Müzayede Adı";
            this.txtMuzayedeAdi.ReadOnly = false;
            this.txtMuzayedeAdi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMuzayedeAdi.SelectedText = "";
            this.txtMuzayedeAdi.SelectionLength = 0;
            this.txtMuzayedeAdi.SelectionStart = 0;
            this.txtMuzayedeAdi.ShortcutsEnabled = true;
            this.txtMuzayedeAdi.Size = new System.Drawing.Size(250, 46);
            this.txtMuzayedeAdi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMuzayedeAdi.TabIndex = 5;
            this.txtMuzayedeAdi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMuzayedeAdi.TextMarginBottom = 0;
            this.txtMuzayedeAdi.TextMarginLeft = 3;
            this.txtMuzayedeAdi.TextMarginTop = 1;
            this.txtMuzayedeAdi.TextPlaceholder = "Müzayede Adı";
            this.txtMuzayedeAdi.UseSystemPasswordChar = false;
            this.txtMuzayedeAdi.WordWrap = true;
            // 
            // txtMuzayedeBaslangic
            // 
            this.txtMuzayedeBaslangic.AcceptsReturn = false;
            this.txtMuzayedeBaslangic.AcceptsTab = false;
            this.txtMuzayedeBaslangic.AnimationSpeed = 200;
            this.txtMuzayedeBaslangic.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMuzayedeBaslangic.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMuzayedeBaslangic.AutoSizeHeight = true;
            this.txtMuzayedeBaslangic.BackColor = System.Drawing.Color.Transparent;
            this.txtMuzayedeBaslangic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMuzayedeBaslangic.BackgroundImage")));
            this.txtMuzayedeBaslangic.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtMuzayedeBaslangic.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtMuzayedeBaslangic.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtMuzayedeBaslangic.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtMuzayedeBaslangic.BorderRadius = 1;
            this.txtMuzayedeBaslangic.BorderThickness = 1;
            this.txtMuzayedeBaslangic.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMuzayedeBaslangic.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeBaslangic.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMuzayedeBaslangic.DefaultText = "";
            this.txtMuzayedeBaslangic.FillColor = System.Drawing.Color.White;
            this.txtMuzayedeBaslangic.HideSelection = true;
            this.txtMuzayedeBaslangic.IconLeft = null;
            this.txtMuzayedeBaslangic.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeBaslangic.IconPadding = 10;
            this.txtMuzayedeBaslangic.IconRight = null;
            this.txtMuzayedeBaslangic.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeBaslangic.Lines = new string[0];
            this.txtMuzayedeBaslangic.Location = new System.Drawing.Point(42, 364);
            this.txtMuzayedeBaslangic.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtMuzayedeBaslangic.MaxLength = 30;
            this.txtMuzayedeBaslangic.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMuzayedeBaslangic.Modified = false;
            this.txtMuzayedeBaslangic.Multiline = false;
            this.txtMuzayedeBaslangic.Name = "txtMuzayedeBaslangic";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeBaslangic.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMuzayedeBaslangic.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeBaslangic.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeBaslangic.OnIdleState = stateProperties28;
            this.txtMuzayedeBaslangic.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtMuzayedeBaslangic.PasswordChar = '\0';
            this.txtMuzayedeBaslangic.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMuzayedeBaslangic.PlaceholderText = "Müzayede Başlangıç Tarihi";
            this.txtMuzayedeBaslangic.ReadOnly = false;
            this.txtMuzayedeBaslangic.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMuzayedeBaslangic.SelectedText = "";
            this.txtMuzayedeBaslangic.SelectionLength = 0;
            this.txtMuzayedeBaslangic.SelectionStart = 0;
            this.txtMuzayedeBaslangic.ShortcutsEnabled = true;
            this.txtMuzayedeBaslangic.Size = new System.Drawing.Size(250, 46);
            this.txtMuzayedeBaslangic.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMuzayedeBaslangic.TabIndex = 6;
            this.txtMuzayedeBaslangic.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMuzayedeBaslangic.TextMarginBottom = 0;
            this.txtMuzayedeBaslangic.TextMarginLeft = 3;
            this.txtMuzayedeBaslangic.TextMarginTop = 1;
            this.txtMuzayedeBaslangic.TextPlaceholder = "Müzayede Başlangıç Tarihi";
            this.txtMuzayedeBaslangic.UseSystemPasswordChar = false;
            this.txtMuzayedeBaslangic.WordWrap = true;
            // 
            // txtMuzayedeBitis
            // 
            this.txtMuzayedeBitis.AcceptsReturn = false;
            this.txtMuzayedeBitis.AcceptsTab = false;
            this.txtMuzayedeBitis.AnimationSpeed = 200;
            this.txtMuzayedeBitis.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMuzayedeBitis.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMuzayedeBitis.AutoSizeHeight = true;
            this.txtMuzayedeBitis.BackColor = System.Drawing.Color.Transparent;
            this.txtMuzayedeBitis.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMuzayedeBitis.BackgroundImage")));
            this.txtMuzayedeBitis.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtMuzayedeBitis.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtMuzayedeBitis.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtMuzayedeBitis.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtMuzayedeBitis.BorderRadius = 1;
            this.txtMuzayedeBitis.BorderThickness = 1;
            this.txtMuzayedeBitis.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMuzayedeBitis.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeBitis.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMuzayedeBitis.DefaultText = "";
            this.txtMuzayedeBitis.FillColor = System.Drawing.Color.White;
            this.txtMuzayedeBitis.HideSelection = true;
            this.txtMuzayedeBitis.IconLeft = null;
            this.txtMuzayedeBitis.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeBitis.IconPadding = 10;
            this.txtMuzayedeBitis.IconRight = null;
            this.txtMuzayedeBitis.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMuzayedeBitis.Lines = new string[0];
            this.txtMuzayedeBitis.Location = new System.Drawing.Point(42, 418);
            this.txtMuzayedeBitis.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtMuzayedeBitis.MaxLength = 30;
            this.txtMuzayedeBitis.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMuzayedeBitis.Modified = false;
            this.txtMuzayedeBitis.Multiline = false;
            this.txtMuzayedeBitis.Name = "txtMuzayedeBitis";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeBitis.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMuzayedeBitis.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeBitis.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMuzayedeBitis.OnIdleState = stateProperties32;
            this.txtMuzayedeBitis.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtMuzayedeBitis.PasswordChar = '\0';
            this.txtMuzayedeBitis.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMuzayedeBitis.PlaceholderText = "Müzayede Bitiş Tarihi";
            this.txtMuzayedeBitis.ReadOnly = false;
            this.txtMuzayedeBitis.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMuzayedeBitis.SelectedText = "";
            this.txtMuzayedeBitis.SelectionLength = 0;
            this.txtMuzayedeBitis.SelectionStart = 0;
            this.txtMuzayedeBitis.ShortcutsEnabled = true;
            this.txtMuzayedeBitis.Size = new System.Drawing.Size(250, 46);
            this.txtMuzayedeBitis.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMuzayedeBitis.TabIndex = 7;
            this.txtMuzayedeBitis.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMuzayedeBitis.TextMarginBottom = 0;
            this.txtMuzayedeBitis.TextMarginLeft = 3;
            this.txtMuzayedeBitis.TextMarginTop = 1;
            this.txtMuzayedeBitis.TextPlaceholder = "Müzayede Bitiş Tarihi";
            this.txtMuzayedeBitis.UseSystemPasswordChar = false;
            this.txtMuzayedeBitis.WordWrap = true;
            // 
            // btnKaydet
            // 
            this.btnKaydet.ActiveBorderThickness = 1;
            this.btnKaydet.ActiveCornerRadius = 20;
            this.btnKaydet.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnKaydet.ActiveForecolor = System.Drawing.Color.White;
            this.btnKaydet.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnKaydet.BackColor = System.Drawing.Color.White;
            this.btnKaydet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKaydet.BackgroundImage")));
            this.btnKaydet.ButtonText = "KAYDET";
            this.btnKaydet.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnKaydet.Font = new System.Drawing.Font("Corbel", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnKaydet.ForeColor = System.Drawing.Color.IndianRed;
            this.btnKaydet.IdleBorderThickness = 1;
            this.btnKaydet.IdleCornerRadius = 20;
            this.btnKaydet.IdleFillColor = System.Drawing.Color.White;
            this.btnKaydet.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnKaydet.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnKaydet.Location = new System.Drawing.Point(82, 559);
            this.btnKaydet.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.btnKaydet.Name = "btnKaydet";
            this.btnKaydet.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btnKaydet.Size = new System.Drawing.Size(170, 44);
            this.btnKaydet.TabIndex = 8;
            this.btnKaydet.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnKaydet.Click += new System.EventHandler(this.btnKaydet_Click);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.radioButton1);
            this.bunifuGroupBox1.Controls.Add(this.txtUcret);
            this.bunifuGroupBox1.Controls.Add(this.txtAdi);
            this.bunifuGroupBox1.Controls.Add(this.btnKaydet);
            this.bunifuGroupBox1.Controls.Add(this.txtSoyad);
            this.bunifuGroupBox1.Controls.Add(this.txtMuzayedeBitis);
            this.bunifuGroupBox1.Controls.Add(this.txtTC);
            this.bunifuGroupBox1.Controls.Add(this.txtMuzayedeBaslangic);
            this.bunifuGroupBox1.Controls.Add(this.txtTelefon);
            this.bunifuGroupBox1.Controls.Add(this.txtMuzayedeAdi);
            this.bunifuGroupBox1.Controls.Add(this.txtEmail);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Adobe Garamond Pro Bold", 13.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(537, 52);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(328, 614);
            this.bunifuGroupBox1.TabIndex = 9;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Müşteri Bilgileri";
            // 
            // radioButton1
            // 
            this.radioButton1.AutoSize = true;
            this.radioButton1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.radioButton1.Font = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.radioButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.radioButton1.Location = new System.Drawing.Point(106, 525);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new System.Drawing.Size(123, 24);
            this.radioButton1.TabIndex = 11;
            this.radioButton1.TabStop = true;
            this.radioButton1.Text = "Ücret Ödendi";
            this.radioButton1.UseVisualStyleBackColor = true;
            // 
            // txtUcret
            // 
            this.txtUcret.AcceptsReturn = false;
            this.txtUcret.AcceptsTab = false;
            this.txtUcret.AnimationSpeed = 200;
            this.txtUcret.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUcret.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUcret.AutoSizeHeight = true;
            this.txtUcret.BackColor = System.Drawing.Color.Transparent;
            this.txtUcret.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUcret.BackgroundImage")));
            this.txtUcret.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtUcret.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtUcret.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtUcret.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtUcret.BorderRadius = 1;
            this.txtUcret.BorderThickness = 1;
            this.txtUcret.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUcret.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUcret.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUcret.DefaultText = "";
            this.txtUcret.FillColor = System.Drawing.Color.White;
            this.txtUcret.HideSelection = true;
            this.txtUcret.IconLeft = null;
            this.txtUcret.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUcret.IconPadding = 10;
            this.txtUcret.IconRight = null;
            this.txtUcret.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUcret.Lines = new string[0];
            this.txtUcret.Location = new System.Drawing.Point(42, 472);
            this.txtUcret.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtUcret.MaxLength = 20;
            this.txtUcret.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUcret.Modified = false;
            this.txtUcret.Multiline = false;
            this.txtUcret.Name = "txtUcret";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUcret.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUcret.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUcret.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUcret.OnIdleState = stateProperties36;
            this.txtUcret.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtUcret.PasswordChar = '\0';
            this.txtUcret.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUcret.PlaceholderText = "Ücret";
            this.txtUcret.ReadOnly = false;
            this.txtUcret.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUcret.SelectedText = "";
            this.txtUcret.SelectionLength = 0;
            this.txtUcret.SelectionStart = 0;
            this.txtUcret.ShortcutsEnabled = true;
            this.txtUcret.Size = new System.Drawing.Size(250, 46);
            this.txtUcret.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUcret.TabIndex = 11;
            this.txtUcret.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUcret.TextMarginBottom = 0;
            this.txtUcret.TextMarginLeft = 3;
            this.txtUcret.TextMarginTop = 1;
            this.txtUcret.TextPlaceholder = "Ücret";
            this.txtUcret.UseSystemPasswordChar = false;
            this.txtUcret.WordWrap = true;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.label1);
            this.bunifuGroupBox2.Controls.Add(this.lblUcret);
            this.bunifuGroupBox2.Controls.Add(this.btnHesapla);
            this.bunifuGroupBox2.Controls.Add(this.txtBitis);
            this.bunifuGroupBox2.Controls.Add(this.txtBaslangic);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Adobe Garamond Pro Bold", 13.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(139, 235);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(322, 251);
            this.bunifuGroupBox2.TabIndex = 10;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Hesap";
            // 
            // lblUcret
            // 
            this.lblUcret.AllowParentOverrides = false;
            this.lblUcret.AutoEllipsis = false;
            this.lblUcret.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblUcret.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblUcret.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblUcret.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.lblUcret.Location = new System.Drawing.Point(140, 204);
            this.lblUcret.Name = "lblUcret";
            this.lblUcret.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUcret.Size = new System.Drawing.Size(16, 20);
            this.lblUcret.TabIndex = 11;
            this.lblUcret.Text = "00";
            this.lblUcret.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblUcret.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnHesapla
            // 
            this.btnHesapla.ActiveBorderThickness = 1;
            this.btnHesapla.ActiveCornerRadius = 20;
            this.btnHesapla.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnHesapla.ActiveForecolor = System.Drawing.Color.White;
            this.btnHesapla.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnHesapla.BackColor = System.Drawing.Color.White;
            this.btnHesapla.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHesapla.BackgroundImage")));
            this.btnHesapla.ButtonText = "HESAPLA";
            this.btnHesapla.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnHesapla.Font = new System.Drawing.Font("Corbel", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnHesapla.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnHesapla.IdleBorderThickness = 1;
            this.btnHesapla.IdleCornerRadius = 20;
            this.btnHesapla.IdleFillColor = System.Drawing.Color.White;
            this.btnHesapla.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnHesapla.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.btnHesapla.Location = new System.Drawing.Point(76, 149);
            this.btnHesapla.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.btnHesapla.Name = "btnHesapla";
            this.btnHesapla.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btnHesapla.Size = new System.Drawing.Size(170, 44);
            this.btnHesapla.TabIndex = 8;
            this.btnHesapla.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHesapla.Click += new System.EventHandler(this.btnHesapla_Click);
            // 
            // txtBitis
            // 
            this.txtBitis.AcceptsReturn = false;
            this.txtBitis.AcceptsTab = false;
            this.txtBitis.AnimationSpeed = 200;
            this.txtBitis.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBitis.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBitis.AutoSizeHeight = true;
            this.txtBitis.BackColor = System.Drawing.Color.Transparent;
            this.txtBitis.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBitis.BackgroundImage")));
            this.txtBitis.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtBitis.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtBitis.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtBitis.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtBitis.BorderRadius = 1;
            this.txtBitis.BorderThickness = 1;
            this.txtBitis.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBitis.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBitis.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBitis.DefaultText = "";
            this.txtBitis.FillColor = System.Drawing.Color.White;
            this.txtBitis.HideSelection = true;
            this.txtBitis.IconLeft = null;
            this.txtBitis.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBitis.IconPadding = 10;
            this.txtBitis.IconRight = null;
            this.txtBitis.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBitis.Lines = new string[0];
            this.txtBitis.Location = new System.Drawing.Point(42, 94);
            this.txtBitis.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtBitis.MaxLength = 30;
            this.txtBitis.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBitis.Modified = false;
            this.txtBitis.Multiline = false;
            this.txtBitis.Name = "txtBitis";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBitis.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBitis.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBitis.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBitis.OnIdleState = stateProperties40;
            this.txtBitis.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtBitis.PasswordChar = '\0';
            this.txtBitis.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBitis.PlaceholderText = "Müzayede Bitiş Tarihi";
            this.txtBitis.ReadOnly = false;
            this.txtBitis.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBitis.SelectedText = "";
            this.txtBitis.SelectionLength = 0;
            this.txtBitis.SelectionStart = 0;
            this.txtBitis.ShortcutsEnabled = true;
            this.txtBitis.Size = new System.Drawing.Size(250, 46);
            this.txtBitis.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBitis.TabIndex = 7;
            this.txtBitis.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBitis.TextMarginBottom = 0;
            this.txtBitis.TextMarginLeft = 3;
            this.txtBitis.TextMarginTop = 1;
            this.txtBitis.TextPlaceholder = "Müzayede Bitiş Tarihi";
            this.txtBitis.UseSystemPasswordChar = false;
            this.txtBitis.WordWrap = true;
            // 
            // txtBaslangic
            // 
            this.txtBaslangic.AcceptsReturn = false;
            this.txtBaslangic.AcceptsTab = false;
            this.txtBaslangic.AnimationSpeed = 200;
            this.txtBaslangic.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBaslangic.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBaslangic.AutoSizeHeight = true;
            this.txtBaslangic.BackColor = System.Drawing.Color.Transparent;
            this.txtBaslangic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBaslangic.BackgroundImage")));
            this.txtBaslangic.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtBaslangic.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtBaslangic.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            this.txtBaslangic.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            this.txtBaslangic.BorderRadius = 1;
            this.txtBaslangic.BorderThickness = 1;
            this.txtBaslangic.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBaslangic.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBaslangic.DefaultFont = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBaslangic.DefaultText = "";
            this.txtBaslangic.FillColor = System.Drawing.Color.White;
            this.txtBaslangic.HideSelection = true;
            this.txtBaslangic.IconLeft = null;
            this.txtBaslangic.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBaslangic.IconPadding = 10;
            this.txtBaslangic.IconRight = null;
            this.txtBaslangic.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBaslangic.Lines = new string[0];
            this.txtBaslangic.Location = new System.Drawing.Point(42, 40);
            this.txtBaslangic.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtBaslangic.MaxLength = 30;
            this.txtBaslangic.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBaslangic.Modified = false;
            this.txtBaslangic.Multiline = false;
            this.txtBaslangic.Name = "txtBaslangic";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBaslangic.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBaslangic.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(220)))), ((int)(((byte)(222)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBaslangic.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(65)))), ((int)(((byte)(142)))));
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBaslangic.OnIdleState = stateProperties44;
            this.txtBaslangic.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.txtBaslangic.PasswordChar = '\0';
            this.txtBaslangic.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBaslangic.PlaceholderText = "Müzayede Başlangıç Tarihi";
            this.txtBaslangic.ReadOnly = false;
            this.txtBaslangic.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBaslangic.SelectedText = "";
            this.txtBaslangic.SelectionLength = 0;
            this.txtBaslangic.SelectionStart = 0;
            this.txtBaslangic.ShortcutsEnabled = true;
            this.txtBaslangic.Size = new System.Drawing.Size(250, 46);
            this.txtBaslangic.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBaslangic.TabIndex = 6;
            this.txtBaslangic.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBaslangic.TextMarginBottom = 0;
            this.txtBaslangic.TextMarginLeft = 3;
            this.txtBaslangic.TextMarginTop = 1;
            this.txtBaslangic.TextPlaceholder = "Müzayede Başlangıç Tarihi";
            this.txtBaslangic.UseSystemPasswordChar = false;
            this.txtBaslangic.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Adobe Garamond Pro Bold", 10.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label1.Location = new System.Drawing.Point(75, 204);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(55, 22);
            this.label1.TabIndex = 11;
            this.label1.Text = "Ücret:";
            // 
            // frmMuzayedeEkle
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1051, 720);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Font = new System.Drawing.Font("Corbel", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Name = "frmMuzayedeEkle";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MuzayedeEkle";
            this.Load += new System.EventHandler(this.frmMuzayedeEkle_Load);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtAdi;
        private Bunifu.UI.WinForms.BunifuTextBox txtSoyad;
        private Bunifu.UI.WinForms.BunifuTextBox txtTC;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefon;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtMuzayedeAdi;
        private Bunifu.UI.WinForms.BunifuTextBox txtMuzayedeBaslangic;
        private Bunifu.UI.WinForms.BunifuTextBox txtMuzayedeBitis;
        private Bunifu.Framework.UI.BunifuThinButton2 btnKaydet;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.Framework.UI.BunifuThinButton2 btnHesapla;
        private Bunifu.UI.WinForms.BunifuTextBox txtBitis;
        private Bunifu.UI.WinForms.BunifuTextBox txtBaslangic;
        private Bunifu.UI.WinForms.BunifuLabel lblUcret;
        private Bunifu.UI.WinForms.BunifuTextBox txtUcret;
        private System.Windows.Forms.RadioButton radioButton1;
        private System.Windows.Forms.Label label1;
    }
}